<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromCollection;
use App\models\raisoni\ConsumptionReport;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\Exportable;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Events\AfterSheet;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;
use App\models\raisoni\SessionsMaster;
use DB;

class ExamConsumptionReportExport implements FromCollection, WithCustomStartCell , WithHeadings,WithEvents, ShouldAutoSize

{
    protected $exam; 

    function __construct($exam) {
        $this->exam = $exam;
    }
    /**
    * @return \Illuminate\Support\Collection
    */
    public function collection()
    {
        
        $where_str    = "1 = ?";
        $where_params = array(1);   
        DB::statement(DB::raw('set @rownum=0'));   
        $columns = [DB::raw('@rownum  := @rownum  + 1 AS rownum'),'programme','department','scheme','term','section','department as Department'];

        if (!empty($this->exam)) {
            $exam = $this->exam;
            $where_str .= " AND (examination = '$exam')";
        }

        $ExamConsumptionReportExport = ConsumptionReport::select($columns)
        		->groupBy('programme','department','scheme','term','section')
                 ->whereRaw($where_str, $where_params)
                 ->orderBy('programme','asc')
                 ->get()->toArray();

        foreach ($ExamConsumptionReportExport as $key => $value) {


        	$ExamConsumptionReportCount = ConsumptionReport::select('id')
                 ->where('programme',$value['programme'])
                 ->where('department',$value['department'])
                 ->where('scheme',$value['scheme'])
                 ->where('term',$value['term'])
                 ->where('section',$value['section'])
                 ->count();
            $ExamConsumptionReportExport[$key]['Department'] = $ExamConsumptionReportCount;
        }
     	return collect($ExamConsumptionReportExport);

    }

    public function startCell(): string
    {
        return 'A3';
    }
    
    public function headings(): array{
        $row = ['Sr. No.','Degree','Branch','Scheme','Semester','Section','Total Count'];
        return $row;
    }

    public function registerEvents(): array
    {
        $user_data = \auth::guard('admin')->user()->username;

        
        return [
            AfterSheet::class    => function(AfterSheet $event) use ($user_data ){
                $event->sheet->SetCellValue('A1', "Report Generated By : ".$user_data);
                $event->sheet->mergeCells('A1:C1');
                $event->sheet->SetCellValue('D1', "Exam Name : ".$this->exam);
                $cellRange = 'A1:D1'; 
                $event->sheet->getDelegate()->getStyle($cellRange)->getFont()->setBold(true);
                $cellRange = 'A3:g3'; // All headers
                $event->sheet->getDelegate()->getStyle($cellRange)->getFont()->setBold(true);
            },
        ];
    }
}
